apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment-prod
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: sanjeevkt720/jenkins-flask-app
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "0.5"
            memory: "200Mi"
